batch_shuffle: true
batch_size: 128
dataset_size: 50000
decoder:
  dropout: 0.1
  embed_dim: 256
  exp_factor: 4
  heads: 8
  num_layers: 4
device: cpu
drop_last: true
encoder:
  dropout: 0.1
  embed_dim: 256
  exp_factor: 4
  heads: 8
  n_channels: 1
  num_layers: 4
id_shuffle: true
loss_fn: CrossEntropyLoss
n_epochs: 10
optimizer: Adam
optimizer_args:
  lr: 0.0005
  weight_decay: 0.0
patch_size: 16
root_dir: data
save_checkpoint: true
save_dir: checkpoints
save_freq: 1
seed: 42
src_pad_idx: 1
test_split: 0.1
tokenizer_path: tokenizer_clean_1k.txt
train_split: 0.8
trg_pad_idx: 999
val_freq: 1
val_split: 0.1
